[workspace]
members = ["cli", "wasm", "core"]
resolver = "3"

[workspace.dependencies]
pyc_editor = { git = "https://github.com/Svenskithesource/pyc-editor", version = "0.2.0" }
python_marshal = "0.4.2"
yansi = "1.0.1"