[workspace]
members = ["cli", "wasm", "core"]
resolver = "3"

[workspace.dependencies]
pyc_editor = { git = "https://github.com/Svenskithesource/pyc-editor", version = "0.4.1", features = [
    "v310",
    "v311",
    "v312",
    "v313",
] }
python_marshal = "0.4.7"
yansi = "1.0.1"
