[package]
name = "pyfalcon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.43", features = ["cargo"] }
pyc_editor = "0.2.0"
python_marshal = "0.4.2"
yansi = "1.0.1"
core = { path = "../core", package = "pyfalcon-core" }